name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  # Specify your .NET version

      - name: Navigate to project directory
        run: cd LightHouseScanner/LightHouseScanner

      - name: Build the project
        run: dotnet publish -c Release -o out
        working-directory: LightHouseScanner/LightHouseScanner

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./LightHouseScanner/LightHouseScanner/out
